### ISSUE TITLE
Bump Metahandler's v#

### ISSUE THREAD

**Issue by host505** [jsergio123/zips#13]
Hi js,
IIRC in the past you pushed a metahandler update (v.3.0.3) that used kodi's tmdb api key, which you later removed.
However some devs of some very popular add-ons still host in their repos the 3.0.3 version (because, you know, higher is better) and that version now has a banned tmdb api key (which, btw, might be said dev's fault because of that).
So, would you please consider re-uploading Metahandler 3.0.2 to your repo and bumping it's v# to something beyond 3.0.3 so it overrides the one in those repos? (I believe they all have your repo linked to their's, so the override should succeed)
I know it's not your fault and this would be done because some people should know better.
Appreciate all you do regardless.

**Comment by jsergio123** [comment]
The version I pushed programmatically loaded the Official Kodi key. The key was not hardcoded.

This is something I would be willing to do only by the request of the XBMC Foundation.

**Comment by jsergio123** [comment]
see here https://github.com/Eldorados/script.module.metahandler
