### ISSUE TITLE
streamango

### ISSUE THREAD

**Issue by pinoytracker** [jsergio123/zips#14]
Hi jsergio123,
First I would like to say Thank You for your contribution.

I would like to inform you about streamango, error, "Unable to locate video", check the links, and are working properly in the browser

Thanks again

**Comment by jsergio123** [comment]
fixed
https://github.com/jsergio123/script.module.resolveurl/commit/1f57169def9ae72f435bcfede2c08edf6f55de3f
and 
https://github.com/jsergio123/script.module.resolveurl/commit/e215a325fc3191d53fbb0b27daea1281275fdfb7
