### ISSUE TITLE
Ok

### ISSUE THREAD

**Issue by pinoytracker** [jsergio123/zips#15]
Hi Jsergio,

Just want to inform you with loading with "ok sources", it will play a bit then loading animation for some time.

and also a request if possible to resolve the live feed of "ok sources"

Thanks

**Comment by jsergio123** [comment]
ok.ru? It is resolving for me. Please provide an example url.

**Comment by pinoytracker** [comment]
Thanks jsergio
here's the link https://ok.ru/live/868735917685, it stops at around 5 seconds

**Comment by pinoytracker** [comment]
jsergio,
just an update i notice some of the links will play and will stop with loading logo around 5 sec. you need to pause the player, then play it again, then i will continue
