### ISSUE TITLE
enabling metadata breaks Adult Swim addon

### ISSUE THREAD

**Issue by jasonbuechler** [jsergio123/zips#16]
Hi jsergio123 -- big big fan of your AS addon (and big critic of the kodi repo's bs a couple months ago). 

I'm attaching a log, where the action starts at 9:51
- first attempt, default initialization with prior launch attempts: dies
- 2nd attempt, access settings and clear metadata, then launch again: dies
- 3rd attempt, access settings and disable metadata, then launch again: success

[adult-swim-106-broken.txt](https://github.com/jsergio123/zips/files/2090974/adult-swim-106-broken.txt)

**Comment by jsergio123** [comment]
Thanks. I will try to get an update when I get some free time.

**Comment by jasonbuechler** [comment]
Hey, just dropping by to say Adult Swim updated their /videos code a bit, breaking some regex and nesting the key json element for "shows". I made some edits to scraper.py to fix this, and just submitted a merge request... 
...although you don't host the source for the AS addon in this repo, so I unzipped it into the AS addon directory, and left the comments in the code. Probably not the best solution but *shrug*. I appended a "jb" to a v106 zip with my edits in it.
...also it doesn't fix the metadata thing, so I just disabled it in settings.xml in my zip. 

Thanks again for this great addon that I use alllll the time!

**Comment by jasonbuechler** [comment]
JK on the metadata note above -- I did find and patch the problem. One weird show was mucking up the entire works by having an empty run-time. I committed a 2nd update for that in my fork.

**Comment by jasonbuechler** [comment]
Hey I fixed the metadata problem:

```
# "Soft Focus with Jena Friedman" had an empty runtime, killing metadata routines
# meta['duration'] = int(show.runtime) * 60

if str(show.runtime) != '':
    meta['duration'] = int(show.runtime) * 60
else:
    meta['duration'] = 99999

# could probably do without the 'else', but I'm superstitious
``` 

I made some edits to my fork's [metahandler.py](https://github.com/jasonbuechler/jsergio123-zips/blob/master/plugin.video.adultswim/plugin.video.adultswim-1.0.6jb/resources/lib/metahandler.py) to fix this, and submitted a merge request... 
...although I realize you don't host the source for the AS addon in this repo, so it's more a "hey here take this" request. :)  

(I unzipped it into the AS addon directory, and left the comments in the code. Probably not the best solution but *shrug*. I appended a "jb" to a v106 zip with my edits in it.)

Thanks again for this great addon that I use alllll the time!

**Comment by jsergio123** [comment]
new version 1.0.8b
