### ISSUE TITLE
Fix ready: Adult Swim addon broken by adultswim.com updates

### ISSUE THREAD

**Issue by jasonbuechler** [jsergio123/zips#18]
Hey, just dropping by to say Adult Swim updated their /videos code a bit, breaking some regex and nesting the key json element for "shows". Which made the addon totally unable to pull episode offerings. 

I made some edits to my fork's [scraper.py](https://github.com/jasonbuechler/jsergio123-zips/blob/master/plugin.video.adultswim/plugin.video.adultswim-1.0.6jb/resources/lib/scraper.py) to fix this, and submitted a hey-here-take-this request (since you don't have posted code to merge into of course) that includes the workaround for the metadata issue, as well.

```
#shows = re.search("""__AS_INITIAL_DATA__\s*=\s*({.*?});""", response).groups()[0]
shows = re.search("""__AS_INITIAL_STATE__\s*=\s*({.*?})</script>""", response).groups()[0]

#shows = shows["shows"]
shows = shows["showsIndex"]["shows"]
```

**Comment by jsergio123** [comment]
v1.0.8b includes fixes and option to select the bitrate to stream

**Comment by jasonbuechler** [comment]
Thank you!

**Comment by imrelaxed** [comment]
regex broke again, want to help?

**Comment by imrelaxed** [comment]
<script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"description":"Watch free full episodes, online videos, clips and web exclusives at AdultSwim.com.","featuredStream":{"title":"[as] Live Stream","url":"/streams","video":"r0xw2u30R3GchW27yVqlug"},"shows":[{"poster":"https://i.cdn.turner.com/adultswim/big/img/2018/11/09/12ozMouse_PosterImage_1.jpg","slug":"12-oz-mouse","title":"12 oz. Mouse","url":"/videos/12-oz-mouse"},{"poster":"https://i.cdn.turner.com/adultswim/big/img/2019/02/07/CelebPoker_index208x277.jpg","slug":"adult-swim-celebrity-poker-tournament-royale","title":"Adult Swim Celebrity Poker Tournament Royale","url":"/videos/adult-swim-celebrity-poker-tournament-royale"},{"poster":"https://i.cdn.turner.com/adultswim/big/img/2019/01/16/AmericanDad_Posterimage.jpg","slug":"american-dad","title":"American Dad","url":"/videos/american-dad"},{"poster":"https://i.cdn.turner.com/adultswim/big/img/2018/11/09/01_ApolloGauntlet_PosterImage.png.jpg","slug":"apollo-gauntlet","title":"Apollo Gauntlet","url":"/videos/apollo-gauntlet"},{"poster":"https://i.cdn.turner.com/adultswim/big/img/2018/11/15/AquaTeenHungerForce_PosterImage.png","slug":"aqua-teen-hunger-force","title":"Aqua Teen Hunger Force","url":"/videos/aqua-teen-hunger-force"},{"poster":"https://i.cdn.turner.com/adultswim/big/img/2018/06/27/AsSeenOn_PosterImage.jpg","slug":"as-seen-on-adult-swim","title":"As Seen On Adult Swim","url":"/videos/as-seen-on-adult-swim"},
