### ISSUE TITLE
metahandler db not initializing in kodi 18 beta1 with addon

### ISSUE THREAD

**Issue by pewkodi** [jsergio123/zips#19]
I was wondering if you had any insight on why the metahandler db does not initialize in kodi 18 beta 1. I noticed it worked in alpha 1 in coreelec 8.90.2 but nothing afterward. The debug log always showed it not not intializing on doing a tv show or movie search.

Did the kodi devs break it?

Thanks

**Comment by jsergio123** [comment]
what version of the metahandler are you running?

**Comment by pewkodi** [comment]
3.0.2 from the tvaddons repo.

**Comment by jsergio123** [comment]
see here https://github.com/Eldorados/script.module.metahandler
