### ISSUE TITLE
ResolveURL addon

### ISSUE THREAD

**Issue by emadmahdi** [jsergio123/zips#22]
Hello jsergio,

I noticed there is another github user that release new updates to your ResolveURL using your name ... I need to use your addon in my addon ... but i am confused which one should i use because both addons are being updated regularly ... Yours v5.0.38 or the other v6.4.97 ?!!

This is the other addon:
https://github.com/fanfilm/repository.fanfilm/tree/master/zips/script.module.resolveurl

Thank you.

**Comment by solbu** [comment]
This looks like the Fanfilm repository that also included the resolver script, and use github to host the repo. (I had to google it)

Don't know why he changes the version thou.

**Comment by emadmahdi** [comment]
When comparing between both,

I noticed he have 11 websites extra plus 8 modified ... check the attached photo !

i also noticed by installing his repository "fanfilm" ... Your plugin will be overwritten automatically because his version is higher than yours.

.
![resolveurl](https://user-images.githubusercontent.com/7454511/77259664-79d34700-6c59-11ea-9a86-0df4d374aa4a.png)
