### ISSUE TITLE
Zevera plugin

### ISSUE THREAD

**Issue by toshiedrive** [jsergio123/zips#6]
Dear Mr Jsergio. 
Would u please update the Zevera plugin. Ur attention and expertise would be greatly appreciated... Thank you sir.

**Comment by jsergio123** [comment]
their site/server are down

**Comment by toshiedrive** [comment]
Thanks 4 the response and hopefully Zavera will be up soon. Alot of ppl interested in using Zavera subs instead of RD..

**Comment by jsergio123** [comment]
Confirmed zevera working but some of their supported sites are marked as inactive. You can see here http://zevera.com/downloadapi.asmx/GetHosters

Those sites that are inactive will fail to play.
