### ISSUE TITLE
Sort premium sources over non premium

### ISSUE THREAD

**Issue by booyakafoo** [jsergio123/zips#7]
Is it possible to prioritize premium sources over non premium?   Currently with premium sources enabled I will get results sorted like so..

Premium sources 1080
Free source 1080
Premium source 720
Free source 720
Premium source SD
Free source SD

I would like to have the results returned as so.  Is this possible?  Is this up to the addon?   Thanks

Premium sources 1080
Premium source 720
Premium source SD
Free source 1080
Free source 720
Free source SD

**Comment by doko-desuka** [comment]
Hi. I'm not the author but I want to help.

ResolveURL and URLResolver only spit out individual links. The video addons are responsible for collecting them (and sorting them, or not). So yes, its up to the video addon.

**Comment by booyakafoo** [comment]
Thank you

**Comment by Grossdm** [comment]
@scottmbritton, 

Do you have a good addon that returns Debrid links? Ideally, it would allow you to sort results as you've described here.

Doug
