### ISSUE TITLE
apollocdn.cc

### ISSUE THREAD

**Issue by poortuga** [jsergio123/zips#9]
hi Jsergio im always following you and i would like to ask you to add this resolver to your resolverurl please...'http://apollocdn.cc/video/60bd583d7aaaac78/iframe'
thank you

**Comment by jsergio123** [comment]
Video was removed. I need a working example.

**Comment by jsergio123** [comment]
@tvaddonsco [http://i.imgur.com/zIBDvJW.gif](http://i.imgur.com/zIBDvJW.gifl) my current situation

**Comment by poortuga** [comment]
hi Jsergio.
i dont now if the url expires but its under this one''http://gofilmes.me/play.php?l=16629a045a6e6eab
thanks

**Comment by tvaddonsco** [comment]
@jsergio123 OMFG, I am not on Keybase but I am on Telegram tvaddonsdotco if you could message me please :)

**Comment by ib1ub12** [comment]
hey jsergio any chance of a resolve url update soon?
